Implement IAM and bucket configuration reload via signal
panasasinc/minio pull request #2
Opened 2022-10-19 15:47 UTC by akhmialevskiy

## Description

- Implemented IAM configuration reload by SIGUSR1 signal for 'panfs gateway'

## Motivation and Context

## How to test this PR?

- Run minio on the two different nodes in `gateway panfs` mode
- Create `mypanfs1 ` and `mypanfs2` aliases
  ```
  mc alias set mypanfs1 http://node1:9000 minio minio123
  mc alias set mypanfs2 http://node2:9000 minio minio123
  ```
- Create new user for `mypanfs1`
  ```
  mc admin user add mypanfs1/ 'random_user4' 'random_passphrase3
  ```
- Get list of user for `mypanfs1` and  `mypanfs2`.  `mypanfs1` has `random_user4` but  `mypanfs2` has not.
- Send `USR1 ` signal for node2 `kill -s USR1 minio_id`
- Get list of user for `mypanfs1` and  `mypanfs2`. Both have  `random_user4`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-10-24 11:35 UTC, lech-lorens-epam requested changes

2022-10-24 11:35 UTC, lech-lorens-epam commented on cmd/signals.go
> +					if err != nil {
If I am not mistaken, err has already been compared to nil in line 110.

2022-10-25 09:43 UTC, akhmialevskiy commented on cmd/signals.go
> +					if err != nil {
Yes, you are right. Fixed

2022-10-25 10:43 UTC, lech-lorens-epam approved these changes

2022-10-25 10:51 UTC, merged